Authentication and Autorization (#8)
* Add style to CurrentlyShowingPage.

* Add link to navbar for currently showing page

* Create Genre type and use it when fetching genres from API

* Create reusable TertiaryButton component

* Update types based on backend responses

* Fetch all distinct projection times and use them for select options

* Use movies length for number in heading and hide Load More button if movies array is empty

* Render NoMoviesPreview when there is no movies to show

* Make CardList component accept route string in props

* Make CardList component accept route string in props

* Add query params to url string

* Add logic for getting furthest end date of all projections for one movie and use it in paragraph element

* Track state of every MovieCardBig's TimeBadges and change style for clicked/selected one

* Delete state for select options from this component

* Create upcoming movies page and form and other elements for page

* Implement logic for handling selected date range

* Change code so it meets criteria for upcoming movies

* Change logic for filtering currently showing movies

* Create basic MovieDetailsPage structure

* Add placeholders for movie details page

* Create new fontstyle class

* Create font-sm-regular style class

* Create component that shows movie ratings from imdb and rt

* Create css file for that component

* Add classes to MovieDetailsPage elements

* Create MovieCardSmall component

* Create css file for styling MovieCardSmall

* Cretate TicketForm element

* Create css file for TicketForm element

* Add more elements and styles to TicketForm

* Create css file for MovieDetailsPage

* Create reusable VerticalDivider component

* Create container that will render MovieCardSmall components

* Add styles to MovieCardSmallList

* Fetch active movies for See Also part of movie details page

* Add logic for small pagination and fetching movies from API

* Add files to .gitignore

* Create MovieContext for active movies

* Edit context so it stores just content(Movie[])

* Send movie to MovieCardSmall as prop

* Add code that is going to extract id from url params and use it for fetching movie

* Use fetched movie data in MovieDetailsPage

* Send movie as props to every MovieCardSmall

* Make DatePickerBtn accept prop size to render different buttons based on that prop

* Create MovieRoutes file that will contain all routes starting with /movies

* Use MovieRoutes in App.tsx

* Make MovieCardBig clickable - link to MovieDetailsPage

* Change routes for currently showing and upcoming movies to be RESTful

* Add more fields to Movie type

* Use photos and writers fields from Movie to render these informations in MovieDetailsPage

* Render movie details page only if movie is fetched(not null)

* Use Link element to make movie cards clickable

* Remove default style for Link(anchor) elements and import css files

* Change route to new RESTful format

* Style video and photo container in MovieDetailsPage

* Add margins to elements that show movie informations

* Add style to improve element positioning

* Style badges with movie ratings

* Style MovieCardSmallList and cut off title if it is too long to fit in the card

* Add star svg

* Find projection times from movie to render it

* Add horizontal line above buttons

* Import SharedCard.css from another folder

* Make some improvements on images

* Improve images fit in MovieDetailsPage

* Add empty/dummy elements to fill up empty space

* Add cineBh logo to assest and use it in navbar and footer

* Create reusable verticalLine component

* Edit classname

* Use VerticalLine component in other places

* Adjust margins in see also section

* Add iframe element for showing movie trailer

* Resolve problem with vertical line width

* Scroll to the top when user opens new movie

* Create new component for form in MovieDetailsPage

* Style component like on Figma design

* Remove unused logic from DatePickerBtn

* Add select elements for city and cinema to form

* Properly format displayed projection date

* Create MovieDetailsForm type and use it in MovieDetailsForm

* Add return types for type safety

* Render DatePickerBtnSmall components and make them horizontally scrollable

* Add style to select icons and text

* Handle form data in state

* Extract DatePickerBtn type to separate file

* Extract function that is generating DatePickerBtnType array because we use it in more than 1 place

* Create element that is going to be shown for upcoming movies in place where is TicketForm for active movies

* Style the component

* Add bell icon to the drawing

* Add logic for picking date

* Extract notification drawing to separate component

* Improve positioning and margins of elements

* Add condition for rendering elements, based on active or upcoming projections

* Make VenueBar horizontally scrollable

* Buttons on PricingPage are navigating to currently showing movies

* If movie synopsis is short, add some bottom margin to that paragraph

* Buttons for reserving/buying ticket is disabled when form is not fulfilled

* Add basic responsiveness to MovieDetailsPage

* Add route for venues in Header component

* Install .env library and create base path variable

* Use env variable in ApiService

* Uninstall dotenv package because Vite doesn't need it

* remove unused code

* Delete unused code

* Install serve package

* Change name of SharedCard.css to Card.css

* If there is only one image, make it 100% height and 100% width of its container

* Create static.json file that tells railway to always serve index.html file

* Movie details page (#7)

* Add style to CurrentlyShowingPage.

* Add link to navbar for currently showing page

* Create Genre type and use it when fetching genres from API

* Create reusable TertiaryButton component

* Update types based on backend responses

* Fetch all distinct projection times and use them for select options

* Use movies length for number in heading and hide Load More button if movies array is empty

* Render NoMoviesPreview when there is no movies to show

* Make CardList component accept route string in props

* Make CardList component accept route string in props

* Add query params to url string

* Add logic for getting furthest end date of all projections for one movie and use it in paragraph element

* Track state of every MovieCardBig's TimeBadges and change style for clicked/selected one
error: could not apply b97e3a7... Movie details page (#7)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply b97e3a7... Movie details page (#7)
* Delete state for select options from this component

* Create upcoming movies page and form and other elements for page

* Implement logic for handling selected date range

* Change code so it meets criteria for upcoming movies

* Change logic for filtering currently showing movies

* Create basic MovieDetailsPage structure

* Add placeholders for movie details page

* Create new fontstyle class

* Create font-sm-regular style class

* Create component that shows movie ratings from imdb and rt

* Create css file for that component

* Add classes to MovieDetailsPage elements

* Create MovieCardSmall component

* Create css file for styling MovieCardSmall

* Cretate TicketForm element

* Create css file for TicketForm element

* Add more elements and styles to TicketForm

* Create css file for MovieDetailsPage

* Create reusable VerticalDivider component

* Create container that will render MovieCardSmall components

* Add styles to MovieCardSmallList

* Fetch active movies for See Also part of movie details page

* Add logic for small pagination and fetching movies from API

* Add files to .gitignore

* Create MovieContext for active movies

* Edit context so it stores just content(Movie[])

* Send movie to MovieCardSmall as prop

* Add code that is going to extract id from url params and use it for fetching movie

* Use fetched movie data in MovieDetailsPage

* Send movie as props to every MovieCardSmall

* Make DatePickerBtn accept prop size to render different buttons based on that prop

* Create MovieRoutes file that will contain all routes starting with /movies

* Use MovieRoutes in App.tsx

* Make MovieCardBig clickable - link to MovieDetailsPage

* Change routes for currently showing and upcoming movies to be RESTful

* Add more fields to Movie type

* Use photos and writers fields from Movie to render these informations in MovieDetailsPage

* Render movie details page only if movie is fetched(not null)

* Use Link element to make movie cards clickable

* Remove default style for Link(anchor) elements and import css files

* Change route to new RESTful format

* Style video and photo container in MovieDetailsPage

* Add margins to elements that show movie informations

* Add style to improve element positioning

* Style badges with movie ratings

* Style MovieCardSmallList and cut off title if it is too long to fit in the card

* Add star svg

* Find projection times from movie to render it

* Add horizontal line above buttons

* Import SharedCard.css from another folder

* Make some improvements on images

* Improve images fit in MovieDetailsPage

* Add empty/dummy elements to fill up empty space

* Add cineBh logo to assest and use it in navbar and footer

* Create reusable verticalLine component

* Edit classname

* Use VerticalLine component in other places

* Adjust margins in see also section

* Add iframe element for showing movie trailer

* Resolve problem with vertical line width

* Scroll to the top when user opens new movie

* Create new component for form in MovieDetailsPage

* Style component like on Figma design

* Remove unused logic from DatePickerBtn

* Add select elements for city and cinema to form

* Properly format displayed projection date

* Create MovieDetailsForm type and use it in MovieDetailsForm

* Add return types for type safety

* Render DatePickerBtnSmall components and make them horizontally scrollable

* Add style to select icons and text

* Handle form data in state

* Extract DatePickerBtn type to separate file

* Extract function that is generating DatePickerBtnType array because we use it in more than 1 place

* Create element that is going to be shown for upcoming movies in place where is TicketForm for active movies

* Style the component

* Add bell icon to the drawing

* Add logic for picking date

* Extract notification drawing to separate component

* Improve positioning and margins of elements

* Add condition for rendering elements, based on active or upcoming projections

* Make VenueBar horizontally scrollable

* Buttons on PricingPage are navigating to currently showing movies

* If movie synopsis is short, add some bottom margin to that paragraph

* Buttons for reserving/buying ticket is disabled when form is not fulfilled

* Add basic responsiveness to MovieDetailsPage

* Add route for venues in Header component

* Install .env library and create base path variable

* Use env variable in ApiService

* Uninstall dotenv package because Vite doesn't need it

* If there is only one image, make it 100% height and 100% width of its container

* Create Loading indicator component

* Use LoadingIndicator in CurrentlyShowingPage while movies are fetching

* Use LoadingIndicator in UpcomingMoviesPage

* Use LoadingIndicator in MovieDetailsPage

* Create favicon of Cinebh logo and display it instead of vite.svg

* Move favicons to /public/favicons folder

* Use LoadingIndicator in HomePage

* Update README.md

* Create basic structure for AuthContainer component

* Create css file for AuthContainer with basic styles

* Add more elements and style to AuthContainer component

* Create SignUpForm component

* Add styles to SignUpForm

* Create Sign In button in navbar

* Make AuthContainer on top of other content

* Add style to components in AuthContainer

* Adjust style and placement of elements in SignupForm

* Style input elements

* Add more elements to AuthContainer and style them

* Style elements in SignUpForm and create custom checkbox

* Install react-hooks-form and use it to register input fields

* Add form validations

* Check if password and confirm password match

* Add error handling and change color of icons when field is populated

* Improve logic for checking if password fields match

* Make AuthContainer scrollable if its content needs more space than screen height is

* Extract custom checkbox to component

* Clear SignupForm styles

* Extract common styles to AuthForm.css

* Create SignInForm component

* Move common styles to AuthForm.css and delete duplicate code

* Make AuthContainer modal and manage its presence in Header component and make Header fixed to the top

* Use button instead of Link for closing AuthContainer and slightly edit its style

* Remove unnecessary elements (remember me and forgot password)

* Use button instead of Link and improve styling

* Add opacity to background when AuthContainer is opened

* Implement password visibility toggling

* Add state to AuthContainer so it can render SignUp form if user click on that button

* Create PasswordResetContainer that is container for other elements of password reset structure

* Create PasswordResetEmail component that contains form for sending email to server

* Create styles for PasswordResetEmail

* Create elements where reset code will be entered

* Add css file for PasswordResetCode

* Remove arrows of number input

* Allow only one entry in inputs and add functionality for moving focus

* Create element for entering new password

* Add css file for NewPasswordForm

* Extract PasswordToggleIcon to separate component

* Extract AuthHeading to reusable component

* Extract back button and heading to reusable component

* Create file that contains logic for rendering different elements in AuthContainer

* Add logic to for rendering different forms

* Edit components so they fit in rendering logic

* Reorganize code and delete unused styles

* Create element that will be shown after successful auth action

* Add options for AuthSuccess element

* Add transition

* Add logic for rendering AuthSuccess when needed

* Track state of remember me checkbox in SignInForm

* Make auth-container responsive

* Create AuthResponse type for tokens

* Create User type

* When SignUpForm is submitted, store jwt in local storage and fetch user with email from jwt payload

* Create UserContext

* When user is signed up, add it to context

* Extract element/button, that is shown when user is logged in, to separate component

* Create useTokenValidation hook that checks if jwt is expired

* Create ProtectedRoute that will handle checking if user is logged in

* Create element that will be shown when user is not logged in and he hits some protected route

* Update logic for token validation

* Use new elements to handle authentication

* Create RefreshTokenResponse for getting new jwt

* Implement logic for refresh token usage

* Edit Header responsiveness

* Remove unnecessary useTokenValidation call and set user when it is signed in

* Add code that will be executed on app mounting and it will ensure that user stays logged in on when app restarts

* Add userId to local storage when user is signed in/up

* Remove bugs from authentication logic

* Move UserActions style to separate file

* Create button for log out that is opened with click on username in navbar

* Implement logout functionality

* After logging in, redirect user to the page that he tried to access

* After sign up redirect user to home page and delete unnecessary logs to console

* Clean up code in components

* Connect component with API

* Send request for getting reset code

* Send request to change user's password and log in user

* Add changes to align with password reset logic

* Implement resending email

* Handle errors that can occurr during authentication process

* Edit style for log out button